name: Deploy repository to Github Pages

on:
  push:
    branches: [main, stable, develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  stable-build:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
          ref: main
          fetch-depth: "0"
      - run: |
          cd main
          ./build_site.sh ../_site/stable
      - uses: actions/upload-pages-artifact@v3

  develop-build:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: dev
          ref: develop
          fetch-depth: "0"
      - run: |
          cd dev
          ../build_site.sh ../_site/develop
      - uses: actions/upload-pages-artifact@v3

  stable-deploy:
    if: github.ref_name == 'main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: stable-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  develop-deploy:
    if: github.ref_name == 'develop'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: develop-build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
